color0 #212c30
color1 #fd4663
color2 #75bad7
color3 #6b7dc7
color4 #8970c2
color5 #a1ccde
color6 #a3aedc
color7 #f2f2f3
color8 #5e6c72
color9 #fd4663
color10 #75bad7
color11 #6b7dc7
color12 #8970c2
color13 #a1ccde
color14 #a3aedc
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #1a2123
background            #1a2123
foreground            #f2f2f3
selection_foreground  #afb4b6
selection_background  #212c30
active_border_color   #75bad7
inactive_border_color #212c30
url_color             #75bad7

active_tab_foreground   #1b2022
active_tab_background   #75bad7
inactive_tab_foreground #afb4b6
inactive_tab_background #212c30
cursor_trail_color      #afb4b6
