color0 #4b454d
color1 #ffb4ab
color2 #dcb9f8
color3 #d1c1d9
color4 #f3b7bc
color5 #dcb9f8
color6 #d1c1d9
color7 #e8e0e8
color8 #968e98
color9 #ffb4ab
color10 #dcb9f8
color11 #d1c1d9
color12 #f3b7bc
color13 #dcb9f8
color14 #d1c1d9
color15 #e8e0e8

cursor                #e8e0e8
cursor_text_color     #151217
background            #151217
foreground            #e8e0e8
selection_foreground  #cdc4ce
selection_background  #4b454d
active_border_color   #dcb9f8
inactive_border_color #4b454d
url_color             #dcb9f8

active_tab_foreground   #3f2358
active_tab_background   #dcb9f8
inactive_tab_foreground #cdc4ce
inactive_tab_background #4b454d
cursor_trail_color      #cdc4ce
