color0 #212130
color1 #fd4663
color2 #8b8bc1
color3 #9981b1
color4 #ad85ad
color5 #acacd3
color6 #bfafd0
color7 #f2f2f3
color8 #65657a
color9 #fd4663
color10 #8b8bc1
color11 #9981b1
color12 #ad85ad
color13 #acacd3
color14 #bfafd0
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #1a1a23
background            #1a1a23
foreground            #f2f2f3
selection_foreground  #afafb6
selection_background  #212130
active_border_color   #8b8bc1
inactive_border_color #212130
url_color             #8b8bc1

active_tab_foreground   #1b1b22
active_tab_background   #8b8bc1
inactive_tab_foreground #afafb6
inactive_tab_background #212130
cursor_trail_color      #afafb6
