foreground            #ede1d4
background            #18120b
cursor                #ede1d4
selection_foreground  #fadebc
selection_background  #56442a

# Black
color0 #3a342b
color8 #9b8f80
# Red
color1 #ffb4ab
color9 #93000a
# Green
color2 #b7cea2
color10 #394c2b
# Yellow
color3 #ddc3a1
color11 #56442a
# Blue
color4 #f3bd6e
color12 #624000
# Magenta
color5 #7e570f
color13 #4f4539
# Cyan
color6 #ffddb1
color14 #f3bd6e
# White
color7 #ede1d4
color15 #d3c4b4
