foreground            #e2e2e9
background            #111318
cursor                #e2e2e9
selection_foreground  #dbe2f9
selection_background  #3f4759

# Black
color0 #33353a
color8 #8e9099
# Red
color1 #ffb4ab
color9 #93000a
# Green
color2 #debcdf
color10 #583e5b
# Yellow
color3 #bfc6dc
color11 #3f4759
# Blue
color4 #adc6ff
color12 #2b4678
# Magenta
color5 #445e91
color13 #44474f
# Cyan
color6 #d8e2ff
color14 #adc6ff
# White
color7 #e2e2e9
color15 #c4c6d0
