foreground            #e4e1e9
background            #131318
cursor                #e4e1e9
selection_foreground  #e2e0f9
selection_background  #454559

# Black
color0 #35343a
color8 #918f9a
# Red
color1 #ffb4ab
color9 #93000a
# Green
color2 #e9b9d3
color10 #5f3c51
# Yellow
color3 #c6c4dd
color11 #454559
# Blue
color4 #c1c1ff
color12 #404178
# Magenta
color5 #585992
color13 #47464f
# Cyan
color6 #e1dfff
color14 #c1c1ff
# White
color7 #e4e1e9
color15 #c8c5d0
