font_family      ZedMono Nerd Font
font_size        12.0

# Zed Mono looks best at 100% or slightly more for a clean look
modify_font line_height 110%
modify_font letter_spacing 0

# Force Kitty to use the font's internal symbols
symbol_map U+2500-U+257F ZedMono Nerd Font

# Disable ligatures for a more "industrial machine" feel
# disable_ligatures always

# Window padding (in pts)
window_padding_width 15 35
text_composition_strategy 1.0 0

# 1. Allow Matugen to change colors on the fly
allow_remote_control yes
listen_on unix:/tmp/kitty

# 2. Include the file Matugen generates (at the very bottom)
include themes/matugen-theme.conf