color0 #5f3e3b
color1 #ffb4ab
color2 #ffb4ab
color3 #ffb4ab
color4 #ffb874
color5 #ffb4ab
color6 #ffb4ab
color7 #ffdad6
color8 #b08782
color9 #ffb4ab
color10 #ffb4ab
color11 #ffb4ab
color12 #ffb874
color13 #ffb4ab
color14 #ffb4ab
color15 #ffdad6

cursor                #ffdad6
cursor_text_color     #210e0c
background            #210e0c
foreground            #ffdad6
selection_foreground  #eabbb6
selection_background  #5f3e3b
active_border_color   #ffb4ab
inactive_border_color #5f3e3b
url_color             #ffb4ab

active_tab_foreground   #690006
active_tab_background   #ffb4ab
inactive_tab_foreground #eabbb6
inactive_tab_background #5f3e3b
cursor_trail_color      #eabbb6
