color0 #4f4539
color1 #ffb4ab
color2 #f1be6d
color3 #dcc3a1
color4 #b6cea4
color5 #f1be6d
color6 #dcc3a1
color7 #ece1d4
color8 #9b8f80
color9 #ffb4ab
color10 #f1be6d
color11 #dcc3a1
color12 #b6cea4
color13 #f1be6d
color14 #dcc3a1
color15 #ece1d4

cursor                #ece1d4
cursor_text_color     #18130b
background            #18130b
foreground            #ece1d4
selection_foreground  #d2c4b4
selection_background  #4f4539
active_border_color   #f1be6d
inactive_border_color #4f4539
url_color             #f1be6d

active_tab_foreground   #432c00
active_tab_background   #f1be6d
inactive_tab_foreground #d2c4b4
inactive_tab_background #4f4539
cursor_trail_color      #d2c4b4
